
### Login to get Token
# @name login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "username": "tester1",
  "password": "password123"
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWxqdnR1OTAwMDAwYWw4a2ZldWl3Y3RwIiwidXNlcm5hbWUiOiJ0ZXN0ZXIxIiwiaWF0IjoxNzcwOTI2NDQ3LCJleHAiOjE3NzA5MjY1Njd9.XkgvYnCqTGzXEVs4t3069F5od3QR1qTmT8VwE9Qgd2c

### Get Todos (Success)
GET http://localhost:3001/todos
Authorization: Bearer {{token}}

### Create Todo (Success)
# @name createTodo
POST http://localhost:3001/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Test Todo",
    "description": "This is a test todo"
}

### 
@todoId = {{createTodo.response.body.id}}

### Get Valid Todo
GET http://localhost:3001/todos/{{todoId}}
Authorization: Bearer {{token}}

### Update Valid Todo
PATCH http://localhost:3001/todos/{{todoId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Updated Title"
}

### Delete Valid Todo
DELETE http://localhost:3001/todos/{{todoId}}
Authorization: Bearer {{token}}

### Delete Non-Existent Todo (Should return 404 Not Found - Prisma P2025)
DELETE http://localhost:3001/todos/non-existent-id
Authorization: Bearer {{token}}

### Update Non-Existent Todo (Should return 404 Not Found - Prisma P2025)
PATCH http://localhost:3001/todos/non-existent-id
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Should Fail"
}
